/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hammingcode;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frm_Hamming extends javax.swing.JFrame {

    /**
     * Creates new form frm_Hamming
     */
    public frm_Hamming() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_input = new javax.swing.JLabel();
        txt_input = new javax.swing.JTextField();
        btn_input0 = new javax.swing.JButton();
        btn_input1 = new javax.swing.JButton();
        btn_inputclear = new javax.swing.JButton();
        lbl_input1 = new javax.swing.JLabel();
        txt_generated = new javax.swing.JTextField();
        txt_gc1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        txt_gc12 = new javax.swing.JTextField();
        txt_gc13 = new javax.swing.JTextField();
        txt_gc14 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_modified = new javax.swing.JLabel();
        txt_modified = new javax.swing.JTextField();
        btn_modifiedClear = new javax.swing.JButton();
        btn_modified1 = new javax.swing.JButton();
        btn_modified0 = new javax.swing.JButton();
        lbl_generated1 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        txt_gc2 = new javax.swing.JTextField();
        txt_gc3 = new javax.swing.JTextField();
        txt_gc4 = new javax.swing.JTextField();
        txt_gc5 = new javax.swing.JTextField();
        txt_gc7 = new javax.swing.JTextField();
        txt_gc6 = new javax.swing.JTextField();
        txt_gc9 = new javax.swing.JTextField();
        txt_gc8 = new javax.swing.JTextField();
        txt_gc11 = new javax.swing.JTextField();
        txt_gc10 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_cc14 = new javax.swing.JTextField();
        txt_cc13 = new javax.swing.JTextField();
        txt_cc12 = new javax.swing.JTextField();
        txt_cc6 = new javax.swing.JTextField();
        txt_cc7 = new javax.swing.JTextField();
        txt_cc5 = new javax.swing.JTextField();
        txt_cc11 = new javax.swing.JTextField();
        txt_cc10 = new javax.swing.JTextField();
        txt_cc9 = new javax.swing.JTextField();
        txt_cc8 = new javax.swing.JTextField();
        txt_cc2 = new javax.swing.JTextField();
        txt_cc4 = new javax.swing.JTextField();
        txt_cc3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_generated2 = new javax.swing.JLabel();
        txt_correctedCode = new javax.swing.JTextField();
        txt_cc1 = new javax.swing.JTextField();
        btn_compute = new javax.swing.JButton();
        btn_execute = new javax.swing.JButton();
        btn_backspace1 = new javax.swing.JButton();
        btn_backspace2 = new javax.swing.JButton();
        lbl_kesalahan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_reset = new javax.swing.JMenuItem();
        mn_exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mn_how = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hamming Code");
        setName("frm_Hamming"); // NOI18N
        setResizable(false);

        lbl_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_input.setText("ENTER INPUT DATA:");

        txt_input.setEditable(false);

        btn_input0.setText("0");
        btn_input0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_input0ActionPerformed(evt);
            }
        });

        btn_input1.setText("1");
        btn_input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_input1ActionPerformed(evt);
            }
        });

        btn_inputclear.setText("C");
        btn_inputclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputclearActionPerformed(evt);
            }
        });

        lbl_input1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_input1.setText("GENERATED CODE:");

        txt_gc1.setEditable(false);

        jTextField4.setEditable(false);

        jTextField5.setEditable(false);

        jTextField6.setEditable(false);

        jTextField7.setEditable(false);

        jTextField9.setEditable(false);

        jTextField8.setEditable(false);

        jTextField11.setEditable(false);

        jTextField10.setEditable(false);

        jTextField13.setEditable(false);

        jTextField12.setEditable(false);

        txt_gc12.setEditable(false);

        txt_gc13.setEditable(false);

        txt_gc14.setEditable(false);

        jLabel4.setText("p8");

        jLabel3.setText("p4");

        jLabel2.setText("p2");

        jLabel1.setText("p1");

        lbl_modified.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_modified.setText("ENTER THE MODIFIED CODE:");

        txt_modified.setEditable(false);

        btn_modifiedClear.setText("C");
        btn_modifiedClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifiedClearActionPerformed(evt);
            }
        });

        btn_modified1.setText("1");
        btn_modified1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modified1ActionPerformed(evt);
            }
        });

        btn_modified0.setText("0");
        btn_modified0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modified0ActionPerformed(evt);
            }
        });

        lbl_generated1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_generated1.setText("GENERATED CODE:");

        jTextField35.setEditable(false);

        txt_gc2.setEditable(false);

        txt_gc3.setEditable(false);

        txt_gc4.setEditable(false);

        txt_gc5.setEditable(false);

        txt_gc7.setEditable(false);

        txt_gc6.setEditable(false);

        txt_gc9.setEditable(false);

        txt_gc8.setEditable(false);

        txt_gc11.setEditable(false);

        txt_gc10.setEditable(false);

        jTextField46.setEditable(false);

        jTextField47.setEditable(false);

        jTextField48.setEditable(false);

        jLabel9.setText("p8");

        jLabel10.setText("p4");

        jLabel11.setText("p2");

        jLabel12.setText("p1");

        txt_cc14.setEditable(false);

        txt_cc13.setEditable(false);

        txt_cc12.setEditable(false);

        txt_cc6.setEditable(false);

        txt_cc7.setEditable(false);

        txt_cc5.setEditable(false);

        txt_cc11.setEditable(false);

        txt_cc10.setEditable(false);

        txt_cc9.setEditable(false);

        txt_cc8.setEditable(false);

        txt_cc2.setEditable(false);

        txt_cc4.setEditable(false);

        txt_cc3.setEditable(false);

        jLabel17.setText("p4");

        jLabel18.setText("p8");

        jLabel19.setText("p1");

        jLabel20.setText("p2");

        lbl_generated2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_generated2.setText("CORRECTED CODE:");

        txt_cc1.setEditable(false);

        btn_compute.setText("Compute Hamming Code");
        btn_compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_computeActionPerformed(evt);
            }
        });

        btn_execute.setText("Execute Error Correction");
        btn_execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_executeActionPerformed(evt);
            }
        });

        btn_backspace1.setText("<-");
        btn_backspace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backspace1ActionPerformed(evt);
            }
        });

        btn_backspace2.setText("<-");
        btn_backspace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backspace2ActionPerformed(evt);
            }
        });

        lbl_kesalahan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_kesalahan.setForeground(new java.awt.Color(255, 0, 0));
        lbl_kesalahan.setText("SALAH DI BIT KE ... ");

        jMenuBar1.setToolTipText("");

        jMenu1.setText("File");

        mn_reset.setText("Reset");
        mn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_resetActionPerformed(evt);
            }
        });
        jMenu1.add(mn_reset);

        mn_exit.setText("Exit");
        mn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_exitActionPerformed(evt);
            }
        });
        jMenu1.add(mn_exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        mn_how.setText("How to Use");
        mn_how.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_howActionPerformed(evt);
            }
        });
        jMenu2.add(mn_how);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gc1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gc2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gc3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gc4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gc5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gc6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gc7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gc8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gc9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gc10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gc11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gc12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gc13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gc14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cc1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txt_cc14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel17)
                                .addGap(112, 112, 112)
                                .addComponent(jLabel18))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_input)
                            .addComponent(txt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_input0)
                                .addGap(6, 6, 6)
                                .addComponent(btn_input1)
                                .addGap(6, 6, 6)
                                .addComponent(btn_inputclear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_backspace1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_generated1)
                                    .addComponent(lbl_input1)
                                    .addComponent(txt_generated, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_compute, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_modified))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_modified, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_generated2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txt_correctedCode, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_kesalahan))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btn_modified0)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_modified1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_modifiedClear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_backspace2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btn_execute, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lbl_input)
                .addGap(6, 6, 6)
                .addComponent(txt_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_input0)
                    .addComponent(btn_input1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_inputclear)
                        .addComponent(btn_backspace1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_compute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_generated1)
                    .addComponent(lbl_input1))
                .addGap(6, 6, 6)
                .addComponent(txt_generated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gc14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addComponent(lbl_modified)
                .addGap(10, 10, 10)
                .addComponent(txt_modified, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modified0)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_modifiedClear)
                        .addComponent(btn_modified1)
                        .addComponent(btn_backspace2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_execute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_generated2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_correctedCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_kesalahan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cc1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cc14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String inputData = "", modifiedCode = "";
    int counter1=0, counter2=0;
    private void btn_input0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_input0ActionPerformed
        if (counter1 < 10) {
            inputData += 0;
            txt_input.setText(inputData);
            counter1++;
        }
    }//GEN-LAST:event_btn_input0ActionPerformed

    private void btn_input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_input1ActionPerformed
        if (counter1 < 10) {
            inputData += 1;
            txt_input.setText(inputData);
            counter1++;
        }
    }//GEN-LAST:event_btn_input1ActionPerformed

    private void btn_inputclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputclearActionPerformed
        inputData = "";
        txt_input.setText(inputData);
        counter1=0;
    }//GEN-LAST:event_btn_inputclearActionPerformed

    private void btn_modified0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modified0ActionPerformed
        if (counter2 < 14) {
            modifiedCode += 0;
            txt_modified.setText(modifiedCode);
            counter2++;
        }
    }//GEN-LAST:event_btn_modified0ActionPerformed

    private void btn_modified1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modified1ActionPerformed
        if (counter2 < 14) {
            modifiedCode += 1;
            txt_modified.setText(modifiedCode);
            counter2++;
        }
    }//GEN-LAST:event_btn_modified1ActionPerformed

    private void btn_modifiedClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifiedClearActionPerformed
        modifiedCode = "";
        txt_modified.setText(modifiedCode);
        counter2=0;
    }//GEN-LAST:event_btn_modifiedClearActionPerformed

    private void btn_computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_computeActionPerformed
        if ("".equals(txt_input.getText())) {
            JOptionPane.showMessageDialog(null, "Tidak Boleh Kosong");
        }
        else {
            HammingCode(txt_input.getText());
        }
    }//GEN-LAST:event_btn_computeActionPerformed

    private void btn_executeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_executeActionPerformed
        if ("".equals(txt_modified.getText())) {
            JOptionPane.showMessageDialog(null, "Tidak Boleh Kosong");
        }
        else {
            ErrorCheck(txt_modified.getText());
        }
    }//GEN-LAST:event_btn_executeActionPerformed

    private void btn_backspace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backspace1ActionPerformed
        if (counter1 > 0) {
            inputData = inputData.substring(0, inputData.length() - 1);
            txt_input.setText(inputData);
            counter1--;
        }
    }//GEN-LAST:event_btn_backspace1ActionPerformed

    private void btn_backspace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backspace2ActionPerformed
        if (counter2 > 0) {
            modifiedCode = modifiedCode.substring(0, modifiedCode.length() - 1);
            txt_modified.setText(modifiedCode);
            counter2--;
        }
    }//GEN-LAST:event_btn_backspace2ActionPerformed

    private void mn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mn_exitActionPerformed

    private void mn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_resetActionPerformed
        inputData = "";
        modifiedCode = "";
        txt_input.setText(inputData);
        txt_modified.setText(inputData);
        txt_generated.setText("");
        txt_correctedCode.setText("");
        lbl_kesalahan.setText("SALAH DI BIT KE ... ");
        clearGeneratedCode();
        clearCorrectedCode();
        
    }//GEN-LAST:event_mn_resetActionPerformed

    private void mn_howActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_howActionPerformed
        JOptionPane.showMessageDialog(this, "-Enter the bits you want to send in input data textfield, \n it will generate Hamming Code for you. \n\n-Enter the bits you want to repair in modified code textfield, \n it will do the correction and locate the error. \n\nNote: This program uses even parity.", "How to Use", WIDTH);
    }//GEN-LAST:event_mn_howActionPerformed
    
    
    public void HammingCode(String str) {
        int m = str.length();
        int r = 1;
        
        while (Math.pow(2, r) < (m+r+1)) {
            r++;
        }
        
        int []arr = new int[m+r+1];
        int j = 0, k = 0;
        //Isi sementara bit parity dgn angka 8
        for (int i=1; i<arr.length; i++) {
            if (i == Math.pow(2, k)) {
                arr[i] = 8;
                k++;
            }
            else {
                arr[i] = Character.getNumericValue(str.charAt(j));
                j++;
            }
        }
        
        //even parity
        int []temp_arr = new int[arr.length];
        int parity = 0, mult=-1;
        while (parity < r) {
            mult++;
            int counter = 0, counter2 = 0, number = 0;
            for (int i=(int)Math.pow(2, mult); i<arr.length; i++) {
            
                if (counter == Math.pow(2,mult)) {
                    if (counter2 == Math.pow(2, mult)-1) {
                        counter=0;
                        counter2=0;
                    }
                    else {
                        counter2++;
                    }
                }
                else {
//                    debug
                    System.out.println("Array[" + i + "] is being checked... it is equal to " + arr[i]);
                    if (arr[i] == 1) {
                        number++;
                    }
                    counter++;
                }
            }
            int index = (int)Math.pow(2, parity);
            if (number % 2 == 1) {
                temp_arr[index] = 1;
            }
            else {
                temp_arr[index] = 0;
            }
            parity++;
        }
        
        //Letakkan kembali bit parity
        int mult2 = 0;
        while(mult2<r) {
            for (int i=1; i<arr.length ; i++) {
                if (i == Math.pow(2, mult2)) {
                    arr[i] = temp_arr[i];
                }
            }
            mult2++;
        }
        
        
        str = "";
        for (int i=1; i<arr.length; i++) {
            System.out.print(arr[i] + " ");
            str = str + arr[i];
        }
        txt_generated.setText(str);
        codeBox1(arr);
    }
    
    public void ErrorCheck(String str) {
        int m = str.length();
        int[] arr = new int[m+1];
        int r = 1;
        
        while (Math.pow(2, r) < (m+1)) {
            r++;
        }
        int[] p = new int[r];
        
        //debug
        System.out.println("r=" + r);
        
        //simpan ke arr
        int j = 0;
        for (int i=1; i<arr.length; i++) {
            arr[i] = Character.getNumericValue(str.charAt(j));
            j++;
        }
        
        //even parity
        int []temp_arr = new int[arr.length];
        int parity = 0, mult=-1;
        while (parity < r) {
            mult++;
            int counter = 0, counter2 = 0, number = 0;
            for (int i=(int)Math.pow(2, mult); i<arr.length; i++) {
            
                if (counter == Math.pow(2,mult)) {
                    if (counter2 == Math.pow(2, mult)-1) {
                        counter=0;
                        counter2=0;
                    }
                    else {
                        counter2++;
                    }
                }
                else {
//                    debug
                    System.out.println("Array[" + i + "] is being checked... it is equal to " + arr[i]);
                    if (arr[i] == 1) {
                        number++;
                    }
                    counter++;
                }
            }
            int index = (int)Math.pow(2, parity);
            if (number % 2 == 1) {
                p[parity] = index;
            }
            parity++;
        }
        int a = 0;
        for (int i=0; i<r; i++) {
            a += p[i];
        }
        
        if (arr[a] == 0) {
            arr[a] = 1;
        }
        else {
            arr[a] = 0;
        }
        
        str = "";
        for (int i=1; i<arr.length; i++) {
            System.out.print(arr[i] + " ");
            str = str + arr[i];
        }
        txt_correctedCode.setText(str);
        lbl_kesalahan.setText("SALAH DI BIT KE ... " + a);
        System.out.print("Correction at number " + a);
        codeBox2(arr);
    }
    
    public  void codeBox1(int[] arr) {
        clearGeneratedCode();
        try {
            txt_gc1.setText("" + arr[1]);
            txt_gc2.setText("" + arr[2]);
            txt_gc3.setText("" + arr[3]);
            txt_gc4.setText("" + arr[4]);
            txt_gc5.setText("" + arr[5]);
            txt_gc6.setText("" + arr[6]);
            txt_gc7.setText("" + arr[7]);
            txt_gc8.setText("" + arr[8]);
            txt_gc9.setText("" + arr[9]);
            txt_gc10.setText("" + arr[10]);
            txt_gc11.setText("" + arr[11]);
            txt_gc12.setText("" + arr[12]);
            txt_gc13.setText("" + arr[13]);
            txt_gc14.setText("" + arr[14]);
        }
        catch(Exception e) {
            System.err.println(e);
        }
    }
    
    public  void codeBox2(int[] arr) {
        clearCorrectedCode();
        try {
            txt_cc1.setText("" + arr[1]);
            txt_cc2.setText("" + arr[2]);
            txt_cc3.setText("" + arr[3]);
            txt_cc4.setText("" + arr[4]);
            txt_cc5.setText("" + arr[5]);
            txt_cc6.setText("" + arr[6]);
            txt_cc7.setText("" + arr[7]);
            txt_cc8.setText("" + arr[8]);
            txt_cc9.setText("" + arr[9]);
            txt_cc10.setText("" + arr[10]);
            txt_cc11.setText("" + arr[11]);
            txt_cc12.setText("" + arr[12]);
            txt_cc13.setText("" + arr[13]);
            txt_cc14.setText("" + arr[14]);
//            txt_cc14.setBackground(Color.yellow);
        }
        catch(Exception e) {
            System.err.println(e);
        }
    }
    
    public void clearGeneratedCode() {
        //clear generated code
        txt_gc1.setText("");
        txt_gc2.setText("");
        txt_gc3.setText("");
        txt_gc4.setText("");
        txt_gc5.setText("");
        txt_gc6.setText("");
        txt_gc7.setText("");
        txt_gc8.setText("");
        txt_gc9.setText("");
        txt_gc10.setText("");
        txt_gc11.setText("");
        txt_gc12.setText("");
        txt_gc13.setText("");
        txt_gc14.setText("");
    }
    
    public void clearCorrectedCode() {
        //clear corrected code
        txt_cc1.setText("");
        txt_cc2.setText("");
        txt_cc3.setText("");
        txt_cc4.setText("");
        txt_cc5.setText("");
        txt_cc6.setText("");
        txt_cc7.setText("");
        txt_cc8.setText("");
        txt_cc9.setText("");
        txt_cc10.setText("");
        txt_cc11.setText("");
        txt_cc12.setText("");
        txt_cc13.setText("");
        txt_cc14.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Hamming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Hamming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Hamming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Hamming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Hamming().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backspace1;
    private javax.swing.JButton btn_backspace2;
    private javax.swing.JButton btn_compute;
    private javax.swing.JButton btn_execute;
    private javax.swing.JButton btn_input0;
    private javax.swing.JButton btn_input1;
    private javax.swing.JButton btn_inputclear;
    private javax.swing.JButton btn_modified0;
    private javax.swing.JButton btn_modified1;
    private javax.swing.JButton btn_modifiedClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbl_generated1;
    private javax.swing.JLabel lbl_generated2;
    private javax.swing.JLabel lbl_input;
    private javax.swing.JLabel lbl_input1;
    private javax.swing.JLabel lbl_kesalahan;
    private javax.swing.JLabel lbl_modified;
    private javax.swing.JMenuItem mn_exit;
    private javax.swing.JMenuItem mn_how;
    private javax.swing.JMenuItem mn_reset;
    private javax.swing.JTextField txt_cc1;
    private javax.swing.JTextField txt_cc10;
    private javax.swing.JTextField txt_cc11;
    private javax.swing.JTextField txt_cc12;
    private javax.swing.JTextField txt_cc13;
    private javax.swing.JTextField txt_cc14;
    private javax.swing.JTextField txt_cc2;
    private javax.swing.JTextField txt_cc3;
    private javax.swing.JTextField txt_cc4;
    private javax.swing.JTextField txt_cc5;
    private javax.swing.JTextField txt_cc6;
    private javax.swing.JTextField txt_cc7;
    private javax.swing.JTextField txt_cc8;
    private javax.swing.JTextField txt_cc9;
    private javax.swing.JTextField txt_correctedCode;
    private javax.swing.JTextField txt_gc1;
    private javax.swing.JTextField txt_gc10;
    private javax.swing.JTextField txt_gc11;
    private javax.swing.JTextField txt_gc12;
    private javax.swing.JTextField txt_gc13;
    private javax.swing.JTextField txt_gc14;
    private javax.swing.JTextField txt_gc2;
    private javax.swing.JTextField txt_gc3;
    private javax.swing.JTextField txt_gc4;
    private javax.swing.JTextField txt_gc5;
    private javax.swing.JTextField txt_gc6;
    private javax.swing.JTextField txt_gc7;
    private javax.swing.JTextField txt_gc8;
    private javax.swing.JTextField txt_gc9;
    private javax.swing.JTextField txt_generated;
    private javax.swing.JTextField txt_input;
    private javax.swing.JTextField txt_modified;
    // End of variables declaration//GEN-END:variables
}
